# Generated by Django 3.1.5 on 2021-01-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/media/placeholder.png', upload_to='blog/media/img'),
        ),
    ]
