# Generated by Django 3.1.5 on 2021-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210122_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='./media/placeholder.png', upload_to='./media/img'),
        ),
    ]
